modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="quickpiston"
version="1.0.0"
displayName="Quick Piston Rotate"
description="Permet de pivoter instantanément les pistons avec une touche."

[[dependencies.quickpiston]]
modId="create"
type="required"
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"
